新浪 SAE个人项目基于django/1/mysite/urls.py
from django.conf.urls.defaults import *
import os
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'templates','css').replace('\\','/')}),
    (r'^download/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'templates','download').replace('\\','/')}),#'show_indexes':True
    (r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'templates','images').replace('\\','/')}),
    (r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'templates','js').replace('\\','/')}),
        
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^$', 'mysite.views.index_do'),
    (r'^hello$', 'mysite.views.hello'),
    (r'^index$', 'mysite.views.index_do'),
    (r'^search$', 'mysite.views.search_do'),
    (r'^register$','mysite.views.register_do'),
    (r'^download$','mysite.views.download_do'),
    (r'^uploadfile$','mysite.views.uploadfile_do'),
)

新浪 SAE个人项目基于django/1/mysite/myapp/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    name = models.CharField(max_length=30)
    passwd = models.CharField(max_length=40)
    email = models.EmailField()
    def __unicode__(self):
        return u'%s %s' % (self.name, self.email)

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()
    
    def __unicode__(self):
        return u'%s %s' % (self.name, self.address)

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    
    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    
    def __unicode__(self):
        return u'%s %s' % (self.title, self.authors)

新浪 SAE个人项目基于django/1/mysite/myapp/forms.py
#!/usr/bin/python
#coding: utf-8
from django import forms
class UsersForm(forms.Form):
    name = forms.CharField()   
    passwd = forms.CharField(widget=forms.PasswordInput)
    repasswd=forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(required=False)
    
    def clean_repasswd(self):
        repawd = self.cleaned_data['repasswd']
        pawd = self.cleaned_data['passwd']
        if pawd!=repawd:
            raise forms.ValidationError(u'两次输入不一致!')
        return repawd
  
class UploadFileForm(forms.Form):
    file = forms.CharField(max_length=50,label=u'上传后的文件名',required=False)
    filepath = forms.FileField(label=u'上传的文件路径')

新浪 SAE个人项目基于django/1/mysite/myapp/views.py
# Create your views here.

新浪 SAE个人项目基于django/1/mysite/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render_to_response
from mysite.myapp.models import Users
from mysite.myapp.forms import UsersForm,UploadFileForm
import datetime
import downfilelist


#def current_datetime(request):
 #   now = datetime.datetime.now()
  #  return render_to_response('current_datetime.html', {'current_date': now})

def hello(request):
    return HttpResponse("Hello, world! - Django")

def index_do(request):    
    return render_to_response('main.html')

def search_do(request):
    if 'name' in request.GET and request.GET['name']:
        j=request.GET['name']     
        plist=Users.objects.filter(name=j) 
        if len(plist):
            id=plist[0].id
            name=plist[0].name
            print "here"
            return render_to_response('myindex.html',{'id':id,'name':name})
        else:
            print "else"
            #return HttpResponseRedirect('/search')
            return render_to_response('do_search.html')
    else:
        print "default"
        return render_to_response('do_search.html')
"""def search(request):   
    if 'name' in request.GET:
        j=request.GET['name']
        plist=Namebook.objects.filter(name=j)
        if len(plist):
            id=plist[0].id
            name=plist[0].name
            country=plist[0].country
            return render_to_response('myindex.html',{'id':id,'name':name,'country':country})
        return HttpResponseRedirect('/search-form/')"""

def register_do(request):   
    if request.method == 'POST':        
        form = UsersForm(request.POST)
        if form.is_valid():
            user=Users()
            cd = form.cleaned_data    
            user.name=cd['name']
            user.passwd=cd['passwd']
            user.email=cd['email']
            user.save()
            return HttpResponseRedirect('index')
    else:
        form=UsersForm()         
    return render_to_response('register.html', {'form': form})

def uploadfile_do(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data   
            if cd['file']:
                savefilename=cd['file']
            else:
                savefilename=request.FILES['filepath'].name            
            #handle_uploaded_file(savefilename,request.FILES['filepath'])
            #return render_to_response('uploadfile.html', {'form': form,'filenamestr':savefilename})
            handle_uploaded_file2(savefilename)
            return HttpResponseRedirect('index')
    else:
        form = UploadFileForm()    
    return render_to_response('uploadfile.html', {'form': form})

def download_do(request):
    downfiles=downfilelist.getdownfilename()    
    #downfiles=['NASM\xca\xd6\xb2\xe1.pdf']
    return render_to_response('download.html',{'downfiles':downfiles})

def handle_uploaded_file(savefilename,f):
    import locale
    localecd=locale.getdefaultlocale()[1]
    #tofilepath='/media/'+savefilename
    #topath=tofilepath.encode(localecd)
    #print topath,type(topath)
    topath=savefilename.encode(localecd)
    destination = open(topath, 'wb+')
    for chunk in f.chunks():
        destination.write(chunk)
    destination.close()
def handle_uploaded_file2(f):
    import locale    
    import sae.storage
    localecd=locale.getdefaultlocale()[1]
    topath=f.encode(localecd)
    s = sae.storage.Client()
    s.list_domain()
    ob = sae.storage.Object('pieces of data')
    s.put('522828368qqcom',topath,ob)

新浪 SAE个人项目基于django/1/mysite/templates/adminopt.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<link href="incss.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="body">
  <div id="log"><p>{{ your_name }}</p></div>
  <div id="main">
  <center>
    <div><table width="310" border="1">
      <tr>
        <td width="59">{{ id }}</td>
        <td width="99" align="center" valign="middle">{{ name }}</td>
        <td width="130">{{ country }}</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></div>
    </center>
    <div id="left">此处显示  id "left" 的内容</div>
    <div id="right">此处显示  id "right" 的内容</div>
  </div>
  <div id="botton">此处显示  id "botton" 的内容</div>
</div>
</body>
</html>

新浪 SAE个人项目基于django/1/mysite/templates/do_search.html
<html>
<head><title>search查询</title></head>
<body>
   <center>
   <p><H1> 查询系统</H1></p>
   <form action="" method="get">
       <p>查询的用户名:  <input type="text" name="name"></p>       
       <input type="submit" value=" 查找 ">
    </form>
    </center>
</body>
</html>

新浪 SAE个人项目基于django/1/mysite/templates/download.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>下 载</title>
<link href="css/divcss.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="main">
    <div id="top-show">  	
      <div id="logmake"><img src="images/Logo.gif" width="88" height="31" /></div>
      <div id="top-left">
	<a href="index">首页</a>&nbsp;|
	<a href="download">下载</a>&nbsp;|
	<a href="uploadfile">上传文件</a>&nbsp;|
	<a href="">在线应用</a>&nbsp;|
      </div>
      <div id="top-right">
	<a href="admin">管理员登录</a>&nbsp;|
	<a href="register" >注册</a>&nbsp;| 
      </div>
    </div>


    <div id="top">  
    <strong>&nbsp;</strong>
     <hr />
	<div id="left-main"><strong>下载内容:</strong></div>      
	<div id="right-main">     
	  {% for downfile in downfiles %}	    
	      <a href="download/{{ downfile }}"> {{ downfile }} </a>
	      <p></p>	    
	  {% endfor %}  	
	</div>
    </div>
</div>
</body>
</html>

新浪 SAE个人项目基于django/1/mysite/templates/main.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>首 页</title>
<link href="css/divcss.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="main">
  <div id="top-show">  	
    <div id="logmake"><img src="images/Logo.gif" width="88" height="31" /></div>
    <div id="top-left">
      <a href="index">首页</a>&nbsp;|
      <a href="download">下载</a>&nbsp;|
      <a href="uploadfile">上传文件</a>&nbsp;|
      <a href="">在线应用</a>&nbsp;|
    </div>
    <div id="top-right">
          <a href="admin">管理员登录</a>&nbsp;|
          <a href="register" >注册</a>&nbsp;| 
    </div>
  </div>
  
  <div id="top">   
    <strong>主页基于新浪SAE:  Django框架+Python+MySql 制作 </strong>
    <hr />
  </div>
  <div id="diaohang"></div>
  <div id="main-main">
  <h3>JQuery实例  （采用最新版jquery-1.7.1.js）</h3>
  </div>  
  <a id="test" href="http://jquery.com/">jQuery</a> 
  <script src="js/jquery-1.7.1.js"></script> 
   <script> 
     $(document).ready(function(){  
       $("a.test").click(function(event){  
         alert("As you can see, the link no longer took you to jquery.com");  
         event.preventDefault();  
       });  
     });  
   </script> 
   
    <script type="text/javascript">  
        $(document).ready(function()  
        {  
            //动画速度  
            var speed = 500;  
 
            //绑定事件处理  
            $("#btnShow").click(function(event)  
            {  
                //取消事件冒泡  
                event.stopPropagation();  
                //设置弹出层位置  
                var offset = $(event.target).offset();  
                $("#divPop").css({ top: offset.top + $(event.target).height() + "px", left: offset.left });  
                //动画显示  
                $("#divPop").show(speed);  
 
            });  
            //单击空白区域隐藏弹出层  
            $(document).click(function(event) { $("#divPop").hide(speed) });  
            //单击弹出层则自身隐藏  
            $("#divPop").click(function(event) { $("#divPop").hide(speed) });  
        });  
    </script>  
 
  
    <div>  
        <br /><br /><br />  
        <button id="btnShow">显示提示文字</button>  
    </div>  
          
    <!-- 弹出层 -->  
    <div id="divPop" style="background-color: #f0f0f0; border: solid 1px #000000; position: absolute; display:none;  
        width: 300px; height: 100px;">  
        <div style="text-align: center;" >弹出层</div>  
    </div>  

</div>
</body>
</html>

新浪 SAE个人项目基于django/1/mysite/templates/myindex.html
<html>
<head><title>查询结果:...</title></head>
<body>
<center>
<h1>此用户已存在</h1>
<p>用户ID: {{ id }}</p>
<p>用户名: {{ name }}</p>

<form action="search" method="get">
        <input type="text" name="name">
        <input type="submit" value="Search">
    </form>
<a href="/search">返回继续查询</a>
</center>
</body>
</html>

新浪 SAE个人项目基于django/1/mysite/templates/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>用户注册</title>
</head>

<body>
<center>
<h1>用户注册</h1>
<form action="" method="post">
  <table>
    {{ orm.as_table }}
  </table>
	<hr />

        <div class="field">
            {{ form.name.errors }}
            <label for="id_name">用户名:</label>
            {{ form.name }}
        </div>
        <div class="field">
            {{ form.passwd.errors }}
            <label for="id_passwd">密  码:</label>
            {{ form.passwd }}
        </div>
        <div class="field">
            {{  form.repasswd.errors }}
            <label for="id_repasswd">确认密码:</label>
            {{ form.repasswd }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Email:</label>
            {{ form.email }}
        </div>

  <label>
    <input type="reset" name="button" id="button" value="重置" />
  </label>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <label>
    <input type="submit" name="button2" id="button2" value="提交" />
  </label>
</form>

</center>

       

</body>
</html>

新浪 SAE个人项目基于django/1/mysite/templates/uploadfile.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<link href="css/divcss.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="main">

<div id="top-show">  	
    <div id="logmake"><img src="images/Logo.gif" width="88" height="31" /></div>
    <div id="top-left">
      <a href="index">首页</a>&nbsp;|
      <a href="download">下载</a>&nbsp;|
      <a href="uploadfile">上传文件</a>&nbsp;|
      <a href="">在线应用</a>&nbsp;|
    </div>
    <div id="top-right">
          <a href="admin">管理员登录</a>&nbsp;|
          <a href="register" >注册</a>&nbsp;| 
    </div>
    
    <div id="top"><strong> 上传文件 </strong>
    <hr />
  </div>
   <center>
        <form action="" method="post" enctype="multipart/form-data">
               <table>
                    {{ form.as_table }}
               </table>       
            <input name="" type="submit" value="提交" />
         
    	</form>
    </center>
   

</div>
</body>
</html>